/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/sign_in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** create */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "user": {
                     *         "email": "test@example.com",
                     *         "password": "password123"
                     *       }
                     *     }
                     */
                    "application/json": {
                        user: {
                            email: string;
                            password: string;
                        };
                    };
                };
            };
            responses: {
                /** @description returns JWT token on successful login */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "user": {
                         *         "id": 53,
                         *         "email": "test@example.com",
                         *         "display_name": "Altha Collins",
                         *         "profile_image": null
                         *       },
                         *       "token": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1MyIsInNjcCI6InVzZXIiLCJhdWQiOm51bGwsImlhdCI6MTc4Mjc0MjI0OSwiZXhwIjoxNzgyODI4NjQ5LCJqdGkiOiJkYjg1NjQ4Yi0yMzFmLTQwYTYtYWE0MS0wNDlmODBkYWQ0NDIifQ.wVLLu71Pz7rlqUQglYxSvRVIstW5ullnfQD2AkM-AG8"
                         *     }
                         */
                        "application/json": {
                            user: {
                                id: number;
                                email: string;
                                display_name: string;
                                profile_image: unknown;
                            };
                            token: string;
                        };
                    };
                };
                /** @description returns 401 on invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Invalid email or password"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sign_out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** destroy */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description logs out successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "message": "Logged out successfully"
                         *     }
                         */
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sign_up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** create */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "user": {
                     *         "email": "new@example.com",
                     *         "password": "password123",
                     *         "password_confirmation": "password123",
                     *         "display_name": "New User"
                     *       }
                     *     }
                     */
                    "application/json": {
                        user: {
                            email: string;
                            password: string;
                            password_confirmation: string;
                            display_name: string;
                        };
                    };
                };
            };
            responses: {
                /** @description creates a new user and returns JWT token */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "user": {
                         *         "id": 52,
                         *         "email": "new@example.com",
                         *         "display_name": "New User",
                         *         "profile_image": null
                         *       },
                         *       "token": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1MiIsInNjcCI6InVzZXIiLCJhdWQiOm51bGwsImlhdCI6MTc4Mjc0MjI0NywiZXhwIjoxNzgyODI4NjQ3LCJqdGkiOiJmMTkwMWQzMy1jOTQzLTRkOWUtODYxYy1mNGU5MWE3MmEyN2MifQ.0BHDhPzKI2LpjYVedw5MRnfQENFvgltaXAWnLJvryxc"
                         *     }
                         */
                        "application/json": {
                            user: {
                                id: number;
                                email: string;
                                display_name: string;
                                profile_image: unknown;
                            };
                            token: string;
                        };
                    };
                };
                /** @description returns validation errors */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "errors": [
                         *         "Email can't be blank",
                         *         "Password can't be blank",
                         *         "Display name can't be blank"
                         *       ]
                         *     }
                         */
                        "application/json": {
                            errors: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** index */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description returns all interests for the current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example [
                         *       {
                         *         "id": 12,
                         *         "keyword": "Rails",
                         *         "created_at": "2026-06-29T14:10:51.098Z"
                         *       },
                         *       {
                         *         "id": 11,
                         *         "keyword": "React",
                         *         "created_at": "2026-06-29T14:10:51.081Z"
                         *       }
                         *     ]
                         */
                        "application/json": {
                            id: number;
                            keyword: string;
                            created_at: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** create */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "interest": {
                     *         "keyword": "TypeScript"
                     *       }
                     *     }
                     */
                    "application/json": {
                        interest: {
                            keyword: string;
                        };
                    };
                };
            };
            responses: {
                /** @description creates a new interest */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": 13,
                         *       "keyword": "TypeScript",
                         *       "created_at": "2026-06-29T14:10:51.227Z"
                         *     }
                         */
                        "application/json": {
                            id: number;
                            keyword: string;
                            created_at: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** destroy */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 15 */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description deletes the interest */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** update */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 14 */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "interest": {
                     *         "keyword": "Vue"
                     *       }
                     *     }
                     */
                    "application/json": {
                        interest: {
                            keyword: string;
                        };
                    };
                };
            };
            responses: {
                /** @description updates the interest */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": 14,
                         *       "keyword": "Vue",
                         *       "created_at": "2026-06-29T14:10:51.263Z"
                         *     }
                         */
                        "application/json": {
                            id: number;
                            keyword: string;
                            created_at: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** index */
        get: {
            parameters: {
                query?: {
                    /** @example 2024-06-15 */
                    date?: string;
                    /** @example React */
                    tag?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description filters by date */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example [
                         *       {
                         *         "id": 33,
                         *         "title": "React 19 Released",
                         *         "tag": "React",
                         *         "published_at": "2024-06-15T00:00:00.000Z",
                         *         "url": "http://vandervort.example/miki"
                         *       }
                         *     ]
                         */
                        "application/json": {
                            id: number;
                            title: string;
                            tag: string;
                            published_at: string;
                            url: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/news/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** show */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 35 */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description returns news detail including text */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": 35,
                         *       "title": "Detail Test",
                         *       "text": "Full text here",
                         *       "tag": "TypeScript",
                         *       "url": "http://corkery.example/ronald",
                         *       "published_at": "2026-06-17T08:56:13.000Z"
                         *     }
                         */
                        "application/json": {
                            id: number;
                            title: string;
                            text: string;
                            tag: string;
                            url: string;
                            published_at: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** show */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description returns the current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": 64,
                         *       "email": "james_gutmann@bogan.test",
                         *       "display_name": "Marty Prosacco",
                         *       "profile_image": null
                         *     }
                         */
                        "application/json": {
                            id: number;
                            email: string;
                            display_name: string;
                            profile_image: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
