/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/sign_in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** create */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "user": {
                     *         "email": "test@example.com",
                     *         "password": "password123"
                     *       }
                     *     }
                     */
                    "application/json": {
                        user: {
                            email: string;
                            password: string;
                        };
                    };
                };
            };
            responses: {
                /** @description returns JWT token on successful login */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "user": {
                         *         "id": 28,
                         *         "email": "test@example.com",
                         *         "display_name": "Luetta Kassulke",
                         *         "profile_image": null
                         *       },
                         *       "token": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyOCIsInNjcCI6InVzZXIiLCJhdWQiOm51bGwsImlhdCI6MTc4MjY1ODM2NiwiZXhwIjoxNzgyNzQ0NzY2LCJqdGkiOiI3NmJhMmVhNy0yYWE4LTQ0NWItODc3My0zM2UwNjNlYTZhNzEifQ.QTaoQTTVsrO5Oes_nWpI9-zLtTSc0quG-_CICZydFUo"
                         *     }
                         */
                        "application/json": {
                            user: {
                                id: number;
                                email: string;
                                display_name: string;
                                profile_image: unknown;
                            };
                            token: string;
                        };
                    };
                };
                /** @description returns 401 on invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Invalid email or password"
                         *     }
                         */
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sign_out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** destroy */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description logs out successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "message": "Logged out successfully"
                         *     }
                         */
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sign_up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** create */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "user": {
                     *         "email": "new@example.com",
                     *         "password": "password123",
                     *         "password_confirmation": "password123",
                     *         "display_name": "New User"
                     *       }
                     *     }
                     */
                    "application/json": {
                        user: {
                            email: string;
                            password: string;
                            password_confirmation: string;
                            display_name: string;
                        };
                    };
                };
            };
            responses: {
                /** @description creates a new user and returns JWT token */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "user": {
                         *         "id": 27,
                         *         "email": "new@example.com",
                         *         "display_name": "New User",
                         *         "profile_image": null
                         *       },
                         *       "token": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyNyIsInNjcCI6InVzZXIiLCJhdWQiOm51bGwsImlhdCI6MTc4MjY1ODM2NSwiZXhwIjoxNzgyNzQ0NzY1LCJqdGkiOiIwNzQ4M2I5Yi02ZjYwLTRlODgtYTA1OC1lMDA4NjUwMDZiNjcifQ.1be3MMwGYBJwKFjtAmJ0MuH5ksicpeYWY4jF4Gvd-S8"
                         *     }
                         */
                        "application/json": {
                            user: {
                                id: number;
                                email: string;
                                display_name: string;
                                profile_image: unknown;
                            };
                            token: string;
                        };
                    };
                };
                /** @description returns validation errors */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "errors": [
                         *         "Email can't be blank",
                         *         "Password can't be blank",
                         *         "Display name can't be blank"
                         *       ]
                         *     }
                         */
                        "application/json": {
                            errors: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** index */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description returns all interests for the current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example [
                         *       {
                         *         "id": 7,
                         *         "keyword": "Rails",
                         *         "created_at": "2026-06-28T14:52:47.130Z"
                         *       },
                         *       {
                         *         "id": 6,
                         *         "keyword": "React",
                         *         "created_at": "2026-06-28T14:52:47.116Z"
                         *       }
                         *     ]
                         */
                        "application/json": {
                            id: number;
                            keyword: string;
                            created_at: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** create */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "interest": {
                     *         "keyword": "TypeScript"
                     *       }
                     *     }
                     */
                    "application/json": {
                        interest: {
                            keyword: string;
                        };
                    };
                };
            };
            responses: {
                /** @description creates a new interest */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": 8,
                         *       "keyword": "TypeScript",
                         *       "created_at": "2026-06-28T14:52:47.211Z"
                         *     }
                         */
                        "application/json": {
                            id: number;
                            keyword: string;
                            created_at: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** destroy */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 10 */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description deletes the interest */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** update */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 9 */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "interest": {
                     *         "keyword": "Vue"
                     *       }
                     *     }
                     */
                    "application/json": {
                        interest: {
                            keyword: string;
                        };
                    };
                };
            };
            responses: {
                /** @description updates the interest */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": 9,
                         *       "keyword": "Vue",
                         *       "created_at": "2026-06-28T14:52:47.253Z"
                         *     }
                         */
                        "application/json": {
                            id: number;
                            keyword: string;
                            created_at: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** show */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description returns the current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": 35,
                         *       "email": "halina_cassin@lehner-mraz.example",
                         *       "display_name": "Lizabeth Emmerich Esq.",
                         *       "profile_image": null
                         *     }
                         */
                        "application/json": {
                            id: number;
                            email: string;
                            display_name: string;
                            profile_image: unknown;
                        };
                    };
                };
                /** @description invalidates the JWT token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /** @example {} */
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
