source "https://rubygems.org"

ruby file: ".ruby-version"

gem "rails", "~> 8.1.3"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[windows jruby]

# API
gem "rack-cors"
gem "jsonapi-serializer"

# Auth
gem "devise"
gem "devise-jwt"

# Background Jobs
gem "sidekiq"
gem "sidekiq-scheduler"

# Environment
gem "dotenv-rails", groups: [:development, :test]

# HTTP Client
gem "faraday"

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
end

group :test do
  gem "rspec-openapi"
end
